DATASETS:
    TRAIN: ('multiview_h36m_train',)
    #TRAIN: ('h36m_val',)
    TEST: ('multiview_h36m_val', )
    TASK: multiview_keypoint
    DATA_FORMAT: jpg
    IMAGE_SIZE: (256, 256)
    IMAGE_RESIZE: 1. #3.90625 #1000. / 256 
    PREDICT_RESIZE: 1. 
    SCALE_FACTOR: 0.25
    ROT_FACTOR: 30
    H36M:
        TRAIN_SAMPLE: 0
        MAPPING: False
DATALOADER:
    NUM_WORKERS: 15
BACKBONE:
    ENABLED: True
    BODY: epipolarposeR-50
    PRETRAINED: True
    DOWNSAMPLE: 4
SOLVER:
    OPTIMIZER: adam
    BASE_LR: 0.001
    STEPS: (2, 3)
    MAX_EPOCHS: 4
    IMS_PER_BATCH: 16
    CHECKPOINT_PERIOD: 1
EPIPOLAR:
    TOPK: 1
    MERGE: late
    SHARE_WEIGHTS: True 
    ATTENTION: avg
    PARAMETERIZED: ('z',)
    PRETRAINED: False
    ZRESIDUAL: True
    USE_CORRECT_NORMALIZE: True
TEST:
    IMS_PER_BATCH: 1
KEYPOINT:
    HEATMAP_SIZE: (64, 64)
    SIGMA: 8.
    NUM_PTS: 17
    TRIANGULATION: pymvg
    LOSS: joint
    LOSS_PER_JOINT: False
VIS:
    MULTIVIEW: True
OUTPUT_DIR: outs/epipolar/keypoint_h36m_aug
EVAL_FREQ: 1
