DATASETS:
    TRAIN: ('h36m_train',)
    #TRAIN: ('h36m_val',)
    TEST: ('multiview_h36m_val', )
    # TEST: ('h36m_val', )
    TASK: keypoint
    DATA_FORMAT: zip
    IMAGE_SIZE: (256, 256)
    IMAGE_RESIZE: 1. #3.90625 #1000. / 256 
    PREDICT_RESIZE: 1. 
    H36M:
        REAL3D: False
DATALOADER:
    NUM_WORKERS: 4
BACKBONE:
    ENABLED: True
    BODY: poseR-50
    PRETRAINED: True
    DOWNSAMPLE: 4
SOLVER:
    OPTIMIZER: adam
    BASE_LR: 0.001
    STEPS: (20,25,)
    MAX_EPOCHS: 30
    IMS_PER_BATCH: 8
    CHECKPOINT_PERIOD: 1
TEST:
    IMS_PER_BATCH: 1
    MAX_TH: 1
KEYPOINT:
    HEATMAP_SIZE: (64, 64)
    SIGMA: 8.
    #HEATMAP_SIZE: 64
    #SIGMA: 5.6
    NUM_PTS: 20
    LOSS: joint
    TRIANGULATION: pymvg
VIS:
    MULTIVIEW: True
# OUTPUT_DIR: outs/benchmark/keypoint_h36m
OUTPUT_DIR: outs/benchmark/keypoint_h36m_afterfix
EVAL_FREQ: 100