DATASETS:
    TRAIN: ('multiview_h36m_train',)
    #TRAIN: ('h36m_val',)
    TEST: ('multiview_h36m_val', )
    TASK: keypoint
    DATA_FORMAT: zip
    IMAGE_SIZE: (384, 384)
    IMAGE_RESIZE: 1. #3.90625 #1000. / 256 
    PREDICT_RESIZE: 1. 
    H36M:
        TRAIN_SAMPLE: 0
        MAPPING: False
DATALOADER:
    NUM_WORKERS: 10
BACKBONE:
    ENABLED: True
    BODY: poseR-152
    PRETRAINED: True
    #PRETRAINED_WEIGHTS: datasets/pose_resnet_4.5_pixels_human36m.pth
    #PRETRAINED_WEIGHTS: datasets/weights_alg.pth
    #PRETRAINED_WEIGHTS: datasets/320_fusion.pth.tar
    DOWNSAMPLE: 4
    SYNC_BN: False
SOLVER:
    OPTIMIZER: adam
    BASE_LR: 0.001
    STEPS: (20, 25)
    MAX_EPOCHS: 30
    IMS_PER_BATCH: 16
    CHECKPOINT_PERIOD: 1
TEST:
    IMS_PER_BATCH: 1
KEYPOINT:
    HEATMAP_SIZE: (96, 96)
    SIGMA: 12.
    NUM_PTS: 17
    TRIANGULATION: pymvg
    LOSS: joint
    LOSS_PER_JOINT: False
VIS:
    MULTIVIEW: True
OUTPUT_DIR: outs/benchmark/keypoint_h36m_resnet152_384
EVAL_FREQ: 1
